import math
from collections import Counter
from dataclasses import dataclass, field, asdict

import torch
from transformers import PreTrainedTokenizer

from .jamo_utils import get_last_syllable_jamo
from .hash_policy import HashPolicy


@dataclass
class DetectionResult:
    """
    Full detection output for the cyclic-embedding scheme.

    `detected_cnt` may exceed `total_steps` because the detector keeps scanning
    after one full cycle of the payload has been recovered. `accuracy` is
    capped at 1.0 — it reports how much of one payload copy was successfully
    recovered, with extra cycles only contributing to the z-score signal.
    """
    accuracy: float                       # min(detected_cnt, total_steps) / total_steps
    extracted_payload: str                # bit string for one cycle (prefix if incomplete)
    z_score: float                        # against H0: per-Hangul-token Bernoulli(p0)
    detected_cnt: int                     # total advances across all cycles
    total_steps: int                      # bits per payload cycle
    cycles_completed: float               # detected_cnt / total_steps
    n_hangul_trials: int                  # Hangul-bearing tokens examined
    n_tokens_examined: int                # all tokens iterated (post prompt skip, pre special-id filter)
    max_skip_run: int                     # longest consecutive run of Hangul mismatches
    skip_runs: list[int] = field(default_factory=list)
    channel_trials: dict[int, int] = field(default_factory=dict)
    channel_matches: dict[int, int] = field(default_factory=dict)

    def to_dict(self) -> dict:
        d = asdict(self)
        d["channel_trials"] = {str(k): v for k, v in self.channel_trials.items()}
        d["channel_matches"] = {str(k): v for k, v in self.channel_matches.items()}
        return d

    # Backwards-compatible 3-tuple unpacking: `acc, payload, z = result`.
    def __iter__(self):
        return iter((self.accuracy, self.extracted_payload, self.z_score))


class JamoWatermarkDetector:
    """
    Detects and extracts a cyclic-embedded watermark from text generated by
    JamoWatermarkProcessor.

    Non-blind: the detector requires the original message to know each step's
    target bit. With cyclic embedding the detector keeps scanning past the
    first full cycle, so additional matches in later cycles strengthen the
    z-score signal even though they don't add new payload bits.
    """
    def __init__(self, tokenizer: PreTrainedTokenizer, original_message: str,
                 mode: str = 'robustness', k_bits: int = 2,
                 lut: dict[str, dict[int, int]] | None = None):
        self.tokenizer = tokenizer
        self.mode = mode
        self.k_bits = k_bits
        byte_data = original_message.encode('utf-8')
        self.payload = ''.join(format(byte, '08b') for byte in byte_data)
        self.hash_policy = HashPolicy(mode=self.mode, k_bits=self.k_bits, lut=lut)

    def _extract_bits_from_token(self, token_str: str, cycle_step: int, cycle_idx: int) -> int | None:
        """
        Returns the channel-selected hash bits for this token at the given
        (cycle_step, cycle_idx), or None when the token has no Hangul syllable.
        """
        jamo_indices = get_last_syllable_jamo(token_str)
        if jamo_indices is None:
            return None

        channel_idx = self.hash_policy.get_channel_idx(cycle_step, cycle_idx)
        token_hashes = self.hash_policy.calculate_channel_hashes(*jamo_indices)
        return token_hashes[channel_idx]

    def extract_payload(
        self,
        input_ids: torch.LongTensor,
        target_payload: str,
        prompt_length: int = 0,
    ) -> DetectionResult:
        if len(target_payload) % self.k_bits != 0:
            raise ValueError(
                f"target_payload length {len(target_payload)} is not a multiple "
                f"of k_bits={self.k_bits}"
            )
        total_steps = len(target_payload) // self.k_bits
        if total_steps == 0:
            raise ValueError("target_payload must encode at least one step")

        token_ids = input_ids[0].tolist()[prompt_length:]

        step_t = 0
        detected_cnt = 0
        n_hangul_trials = 0
        n_tokens_examined = 0
        recovered_bits: list[str] = []  # captures the first cycle's worth of matched bits

        skip_runs: list[int] = []
        current_skip = 0
        channel_trials: Counter = Counter()
        channel_matches: Counter = Counter()

        for token_id in token_ids:
            n_tokens_examined += 1
            if token_id in self.tokenizer.all_special_ids:
                continue

            cycle_step = step_t % total_steps
            cycle_idx = step_t // total_steps

            token_str = self.tokenizer.convert_ids_to_tokens(token_id)
            extracted_bits = self._extract_bits_from_token(token_str, cycle_step, cycle_idx)

            if extracted_bits is None:
                continue

            n_hangul_trials += 1
            channel_idx = self.hash_policy.get_channel_idx(cycle_step, cycle_idx)
            channel_trials[channel_idx] += 1

            target_bits = int(
                self.payload[cycle_step * self.k_bits : (cycle_step + 1) * self.k_bits],
                2,
            )

            if extracted_bits == target_bits:
                # Capture this match into recovered_bits only during the first cycle —
                # subsequent cycles re-emit the same payload, so they only contribute
                # to detection significance, not to message recovery.
                if step_t < total_steps:
                    recovered_bits.append(format(extracted_bits, f'0{self.k_bits}b'))
                detected_cnt += 1
                step_t += 1
                channel_matches[channel_idx] += 1
                if current_skip > 0:
                    skip_runs.append(current_skip)
                    current_skip = 0
            else:
                current_skip += 1

        if current_skip > 0:
            skip_runs.append(current_skip)

        accuracy = min(detected_cnt, total_steps) / total_steps
        cycles_completed = detected_cnt / total_steps

        p0 = 1.0 / (2 ** self.k_bits)
        if n_hangul_trials > 0:
            expected = n_hangul_trials * p0
            std_dev = math.sqrt(n_hangul_trials * p0 * (1 - p0))
            z_score = (detected_cnt - expected) / std_dev if std_dev > 0 else 0.0
        else:
            z_score = 0.0

        return DetectionResult(
            accuracy=accuracy,
            extracted_payload="".join(recovered_bits),
            z_score=z_score,
            detected_cnt=detected_cnt,
            total_steps=total_steps,
            cycles_completed=cycles_completed,
            n_hangul_trials=n_hangul_trials,
            n_tokens_examined=n_tokens_examined,
            max_skip_run=max(skip_runs) if skip_runs else 0,
            skip_runs=skip_runs,
            channel_trials=dict(channel_trials),
            channel_matches=dict(channel_matches),
        )
